---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpcontainer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumpcontainer
  template:
    metadata:
      labels:
        app: jumpcontainer
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10002
      containers:
        - name: jumpcontainer
          image: ghcr.io/matgoebl/totp-sshd-jumpcontainer:latest
          # imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
          ports:
            - name: sshd
              containerPort: 2222
          env:
            - name: JUMPHOST
              value: "jumpcontainer"
            - name: JUMPUSER
              value: "jumper"
            # - name: JUMPPASS
            #   valueFrom:
            #     secretKeyRef:
            #       name: jumpcontainer-secrets
            #       key: jumppass
            # - name: JUMPTOTP
            #   valueFrom:
            #     secretKeyRef:
            #       name: jumpcontainer-secrets
            #       key: jumptotp
            # - name: JUMPKEY
            #   value: "ssh-rsa ABC...= user@laptop"
---
apiVersion: v1
kind: Service
metadata:
  name: jumpcontainer
  namespace: default
  labels:
    app: jumpcontainer
spec:
  type: LoadBalancer
  ports:
    - name: sshd
      protocol: TCP
      port: 12345
      targetPort: sshd
  selector:
    app: jumpcontainer
---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: jumpcontainer-policy
#   namespace: default
#   labels:
#     app: jumpcontainer
# spec:
#   podSelector:
#     matchLabels:
#       app: jumpcontainer
#   policyTypes:
#     - Ingress
#     - Egress
#   ingress:
#   - ports:
#     - port: 2222
#   egress:
#     - to:
#         - ipBlock:
#             cidr: 10.10.10.10/32  # your target host to jump to
#       ports:
#         - protocol: TCP
#           port: 22
#     - to: # allow connections to kubernetes DNS server
#         - namespaceSelector:
#             matchLabels:
#               kubernetes.io/metadata.name: kube-system
#           podSelector:
#             matchLabels:
#               k8s-app: kube-dns
#       ports:
#         - protocol: UDP
#           port: 53
#         - protocol: TCP
#           port: 53
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: jumpcontainer-secrets
#   namespace: default
#   labels:
#     app: jumpcontainer
# immutable: true
# stringData:
#   jumppass: "123"
#   jumptotp: "LT2MSLFXAW7YT4Z65RVCAO2VFU"
